[platformio]
default_envs = dynamixel_sample

[env:dynamixel_sample]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
check_tool = cppcheck
check_flags =
  cppcheck: --enable=all --inconclusive --force --error-exitcode=1
check_src_filters =
  +<./src>
  +<./lib>
lib_deps =
    m5stack/M5Unified@^0.1.12
    ; lovyan03/LovyanGFX@^1.1.9
    ; powerbroker2/SerialTransfer
    ROBOTIS-GIT/Dynamixel2Arduino
    m5stack/M5AtomS3
    fastled/FastLED
build_src_filter = +<dynamixel_sample.cpp>

[env:dynamixel_setID]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
check_tool = cppcheck
check_flags =
  cppcheck: --enable=all --inconclusive --force --error-exitcode=1
check_src_filters =
  +<./src>
  +<./lib>
lib_deps =
    m5stack/M5Unified@^0.1.12
    m5stack/M5AtomS3
    fastled/FastLED
    ROBOTIS-GIT/Dynamixel2Arduino
build_src_filter = +<dynamixel_setID.cpp>

[env:dynamixel_setBaud]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
check_tool = cppcheck
check_flags =
  cppcheck: --enable=all --inconclusive --force --error-exitcode=1
check_src_filters =
  +<./src>
  +<./lib>
lib_deps =
    m5stack/M5Unified@^0.1.12
    m5stack/M5AtomS3
    fastled/FastLED
    ROBOTIS-GIT/Dynamixel2Arduino
build_src_filter = +<dynamixel_setBaud.cpp>

[env:dynamixel_extended_position]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
check_tool = cppcheck
check_flags =
  cppcheck: --enable=all --inconclusive --force --error-exitcode=1
check_src_filters =
  +<./src>
  +<./lib>
lib_deps =
    m5stack/M5Unified@^0.1.12
    m5stack/M5AtomS3
    fastled/FastLED
    ROBOTIS-GIT/Dynamixel2Arduino
build_src_filter = +<dynamixel_extended_position.cpp>

[env:dynamixel_hold_free]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
check_tool = cppcheck
check_flags =
  cppcheck: --enable=all --inconclusive --force --error-exitcode=1
check_src_filters =
  +<./src>
  +<./lib>
lib_deps =
    m5stack/M5Unified@^0.1.12
    m5stack/M5AtomS3
    fastled/FastLED
    ROBOTIS-GIT/Dynamixel2Arduino
build_src_filter = +<dynamixel_hold_free.cpp>

[env:dynamixel_current]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
check_tool = cppcheck
check_flags =
  cppcheck: --enable=all --inconclusive --force --error-exitcode=1
check_src_filters =
  +<./src>
  +<./lib>
lib_deps =
    m5stack/M5Unified@^0.1.12
    m5stack/M5AtomS3
    fastled/FastLED
    ROBOTIS-GIT/Dynamixel2Arduino
build_src_filter = +<dynamixel_current.cpp>